// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVb-woh4JxwF7ACIQvbW3WGFNxBd0UvTU',
    appId: '1:10821110966:web:7015ab30d065fa51866a17',
    messagingSenderId: '10821110966',
    projectId: 'sharemymeds-80643',
    authDomain: 'sharemymeds-80643.firebaseapp.com',
    storageBucket: 'sharemymeds-80643.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC33H62BG8nX_nV--5OWUNRBLk6RowRY2Q',
    appId: '1:10821110966:android:2d6bc00e15f3f276866a17',
    messagingSenderId: '10821110966',
    projectId: 'sharemymeds-80643',
    storageBucket: 'sharemymeds-80643.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEVKx9F9H_cyyyC23tP4XXkzJrYYAtkus',
    appId: '1:10821110966:ios:f1f5084f68685ae8866a17',
    messagingSenderId: '10821110966',
    projectId: 'sharemymeds-80643',
    storageBucket: 'sharemymeds-80643.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEVKx9F9H_cyyyC23tP4XXkzJrYYAtkus',
    appId: '1:10821110966:ios:f1f5084f68685ae8866a17',
    messagingSenderId: '10821110966',
    projectId: 'sharemymeds-80643',
    storageBucket: 'sharemymeds-80643.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVb-woh4JxwF7ACIQvbW3WGFNxBd0UvTU',
    appId: '1:10821110966:web:c60a7bd6f973e848866a17',
    messagingSenderId: '10821110966',
    projectId: 'sharemymeds-80643',
    authDomain: 'sharemymeds-80643.firebaseapp.com',
    storageBucket: 'sharemymeds-80643.firebasestorage.app',
  );

}